### ISSUE TITLE
Carousel doesn't work in Firefox

### ISSUE THREAD

**Issue by jacobabrennan** [build-rideForLife/build_rideForLife_marketingA#5]
The arrow functions I helped write don't work in Firefox - at least, they're not working in my version of Firefox on Windows 7. This is the exact error I'm getting:
`SyntaxError: missing ; after field definition                carousel.js:44:4`

The line in question read:
`rightButtonClick = () => {`

But I think the error is generated by the code block above it. I think attempting to assign an arrow function as a property of a class in the class definition is nonstandard Javascript. In my experience, Firefox has a more strict JS parser than Chrome, and throws errors and Chrome attempts to recover from.

Instead of using the above strategy, we can do something like the following:
`rightbutton.addEventListener('click', () => this.rightButtonClick());`

**Comment by kimberleehowley** [comment]
We fixed this issue by not only making that above change to calling the method, but also reformatting the methods themselves out of arrow functions and into plain old function syntax.
